# [05/07] 파이썬 6일차 실습예제

## 굿모닝 코딩
https://school.programmers.co.kr/learn/courses/30/lessons/340213

In [26]:
def solution(video_len, pos, op_start, op_end, commands):
    min_answer = ""
    sec_answer = ""
    answer = ""

    # 분으로 바꿔버리기
    min_video_len   = 60 * int(video_len[:2]) + int(video_len[3:])
    min_pos         = 60 * int(pos[:2]) + int(pos[3:])
    min_op_start    = 60 * int(op_start[:2]) + int(op_start[3:])
    min_op_end      = 60 * int(op_end[:2]) + int(op_end[3:])

    for command in commands:
        if min_pos >= min_op_start and min_pos <= min_op_end:
            min_pos = min_op_end

        if command == "next":
            min_pos += 10
        elif command == "prev":
            min_pos -= 10

        if min_pos < 0:
            min_pos = 0
        if min_pos > min_video_len:
            min_pos = min_video_len

    # 마지막 확인
    if min_pos >= min_op_start and min_pos <= min_op_end:
            min_pos = min_op_end

    # 분 정답으로 바꾸기
    if len(str(min_pos // 60)) == 1:
        min_answer = "0" + str(min_pos // 60)
    else:
        min_answer = str(min_pos // 60)
    # 초
    if len(str(min_pos % 60)) == 1:
        sec_answer = "0" + str(min_pos % 60)
    else:
        sec_answer = str(min_pos % 60)

    answer = min_answer + ":" + sec_answer
    return answer

# try - except

- 프로그램이 에러 때문에 멈추지 않게, 에러(예외)를 잡아서 처리하는 방법
- try 문에 에러가 발생했을 때 except 문 실행
```python
try:
    # 에러가 날 수도 있는 코드
except 에러종류 as e:
    # 에러가 났을 때 실행할 코드
    # e에 에러 메세지 담김
finally:
    # 항상 마지막에 실행, 선택사항임
```

# Numpy

In [27]:
import numpy as np
nd1 = np.arange(10)
print(nd1)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
nd1.shape

(10,)

In [29]:
nd1 = np.arange(12).reshape(3,4) # 3 * 4 
print(nd1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
nd1 = np.arange(5)
print(nd1)
nd1 = np.arange(5).reshape(5,1)
print(nd1)
nd1 = np.arange(5).reshape(1,5)
print(nd1)

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]


In [31]:
nd1 = np.arange(5)
print(nd1)
print(nd1 + 3)

[0 1 2 3 4]
[3 4 5 6 7]


In [32]:
nd1 = np.arange(5)
print(nd1)
nd2 = np.arange(5).reshape(5,1)
print(nd2)
print(nd1+nd2)
print(nd1==nd2)

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


In [33]:
nd1 = np.arange(5,20,2) # 5부터 19까지 2씩 늘려서
print(nd1)

[ 5  7  9 11 13 15 17 19]


In [34]:
print(nd1[3:4]) # 4번째 값 반환환

[11]


In [35]:
nd1[nd1 > 12] # 12보다 큰 값 반환환

array([13, 15, 17, 19])

In [36]:
nd1[[True, False, True, True, True, False, True, True]] # True 값만 바노한한

array([ 5,  9, 11, 13, 17, 19])

In [37]:
nd1 = np.arange(6)
print(nd1)

[0 1 2 3 4 5]


In [38]:
nd1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
nd1[:,np.newaxis] # 새로운 축을 추가살 때 사용 1차원 배열을 2차원 배열로 변환
# (5,) 에서 (5, 1)로 변환

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [40]:
# axis= 0 행 방향으로 계산
# axis= 1 열 방향을 계산
# axis= 2 깂이 방향으로 계산산
nd1 = np.arange(24).reshape(2,3,4) # 3행 4열 
print(nd1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [41]:
nd1.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [42]:
nd1.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [43]:
nd1.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [44]:
nd1.mean(axis=(0,1)) # 0축 1축 없애고 전체 계산

array([10., 11., 12., 13.])

In [45]:
nd1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
nd2 = np.zeros_like(nd1) #  n1과 똑같은 모형과 자료형을 가진 배열로 만들고 그 값을 0으로 채움
print(nd2)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [47]:
nd2 = np.ones_like(nd1) # n1과 똑같은 모형과 자료형을 가진 배열로 만들고 그 값을 1로 채움
print(nd2)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [48]:
lst = list(range(10))
nd1 = np.asarray(lst).astype(np.float16) # 리스트를 넘파이 배열로 바꾸고 배열 안의 자료형을 float16으로 변환한다
print(nd1, nd1.shape, nd1.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] (10,) float16


In [49]:
nd2[0,0,3] = 10
print(nd2)

[[[ 1  1  1 10]
  [ 1  1  1  1]
  [ 1  1  1  1]]

 [[ 1  1  1  1]
  [ 1  1  1  1]
  [ 1  1  1  1]]]


In [51]:
# 1, 1, 2
# 1, 2, 3
# 1, 1:3, 2:4
nd2[1,1:3,2:4] = 100
print(nd2)

[[[  1   1   1  10]
  [  1   1   1   1]
  [  1   1   1   1]]

 [[  1   1   1   1]
  [  1   1 100 100]
  [  1   1 100 100]]]


In [52]:
nd1 = np.arange(12).reshape(3,4)
print(nd1)
nd2 = nd1
print(nd2)
nd1[nd1>10] = 100
print(nd1)
print(nd2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10 100]]
[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10 100]]
