In [1]:
import numpy as np
import pandas as pd

## 나이브 베이즈
- 확률 기반의 데이터 분석에 적합

In [2]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
print(cancer.DESCR)

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [3]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(cancer.data,
                                                    cancer.target,
                                                    stratify= cancer.target,
                                                    random_state = 7)

x_train.shape, y_train.shape

((426, 30), (426,))

In [4]:
# 3. 모델 생성 및 학습

from sklearn.naive_bayes import GaussianNB

cancer_nb = GaussianNB()

cancer_nb.fit(x_train, y_train)

pred = cancer_nb.predict(x_test)

In [5]:
# 4. 예측 확인
print(y_test)    # 정답
print(pred)      # 예측값
print(np.mean(y_test == pred))   # 예측 정답률

[1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 1
 0 1 0 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1 0 1 0 0 0 1 1 1 1 0 1 0
 0 1 1 1 1 0 0 0 0 1 0 1 1 0 1 0 1 1 0 1 1 0 1 1 1 0 0 0 1 0 1 0]
[1 0 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 1
 0 1 0 0 1 1 1 0 1 1 1 0 1 1 0 1 0 0 1 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 0 1 0
 0 0 1 1 1 0 0 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 0 1 0 1 0]
0.9230769230769231


In [6]:
# -------------------------------------

# 아이리스 데이터에도 적용

from sklearn.datasets import load_iris
iris = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    stratify=iris.target,
                                                    random_state=7)
iris_nb = GaussianNB()
iris_nb.fit(x_train, y_train)
pred = iris_nb.predict(x_test)
print(y_test)
print(pred)
print(np.mean(y_test==pred))

[0 0 2 1 0 1 0 2 0 2 2 1 0 0 1 2 0 1 2 0 0 2 2 2 1 1 1 1 0 1 1 2 0 0 1 1 2
 2]
[0 0 2 1 0 1 0 2 0 2 2 1 0 0 1 2 0 1 2 0 0 2 2 2 1 1 1 1 0 1 1 2 0 0 1 1 2
 2]
1.0


In [7]:
print(cancer.data.shape)
print(cancer.data)

# 결과: 속성별로 data의 range 차이가 큼

(569, 30)
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [8]:
lst_idx = list(range(1,20))
print(lst_idx)
np.random.shuffle(lst_idx)
print(lst_idx)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[18, 14, 5, 16, 10, 2, 17, 6, 12, 9, 1, 15, 3, 8, 11, 19, 7, 4, 13]


In [9]:
cancer.data[lst_idx[int(20 * 0.7)]]

array([1.578e+01, 1.789e+01, 1.036e+02, 7.810e+02, 9.710e-02, 1.292e-01,
       9.954e-02, 6.606e-02, 1.842e-01, 6.082e-02, 5.058e-01, 9.849e-01,
       3.564e+00, 5.416e+01, 5.771e-03, 4.061e-02, 2.791e-02, 1.282e-02,
       2.008e-02, 4.144e-03, 2.042e+01, 2.728e+01, 1.365e+02, 1.299e+03,
       1.396e-01, 5.609e-01, 3.965e-01, 1.810e-01, 3.792e-01, 1.048e-01])

In [10]:
from sklearn.model_selection import StratifiedShuffleSplit

acc = []
split = StratifiedShuffleSplit(n_splits = 10, test_size = 0.3)

for train_idx, test_idx in split.split(cancer.data, cancer.target):
  print('-' * 30)
  # print(train_idx)
  # print(test_idx)

  cancer_nb = GaussianNB()
  cancer_nb.fit(cancer.data[train_idx], cancer.target[train_idx])
  pred = cancer_nb.predict(cancer.data[test_idx])
  print(np.mean(cancer.target[test_idx] == pred))
  acc.append(np.mean(cancer.target[test_idx] == pred))

np.mean(acc)

------------------------------
0.9415204678362573
------------------------------
0.9532163742690059
------------------------------
0.935672514619883
------------------------------
0.935672514619883
------------------------------
0.9298245614035088
------------------------------
0.9298245614035088
------------------------------
0.9707602339181286
------------------------------
0.9415204678362573
------------------------------
0.9415204678362573
------------------------------
0.9532163742690059


np.float64(0.9432748538011696)

# KNN 써보기

In [11]:
# 데이터 확인
data = cancer.data
target = cancer.target
print(data)
print(target)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [12]:
# 데이터 크기 출력
print(data.shape, target.shape)

(569, 30) (569,)


In [13]:
import numpy as np
# 고유 라벨값과 라벨당 데이터 개수 출력
np.unique(target, return_counts=True)

(array([0, 1]), array([212, 357]))

In [14]:
# 7:3 비율로 데이터 스플릿
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data,
                                                    target,
                                                    test_size=0.3,
                                                    random_state=0)

print(x_train.shape, y_test.shape)

(398, 30) (171,)


In [15]:
# 고유값 출력
np.unique(y_test, return_counts=True)

(array([0, 1]), array([ 63, 108]))

In [16]:
print(np.min(x_train, axis=0))
print(np.max(x_train, axis=0))
print(np.mean(x_train, axis=0))
print(np.std(x_train, axis=0))

[6.981e+00 9.710e+00 4.379e+01 1.435e+02 5.263e-02 1.938e-02 0.000e+00
 0.000e+00 1.060e-01 4.996e-02 1.115e-01 3.628e-01 7.570e-01 7.228e+00
 1.713e-03 2.252e-03 0.000e+00 0.000e+00 7.882e-03 8.948e-04 7.930e+00
 1.202e+01 5.041e+01 1.852e+02 7.117e-02 2.729e-02 0.000e+00 0.000e+00
 1.565e-01 5.504e-02]
[2.811e+01 3.381e+01 1.885e+02 2.501e+03 1.447e-01 3.114e-01 4.268e-01
 2.012e-01 3.040e-01 9.744e-02 2.873e+00 4.885e+00 2.198e+01 5.422e+02
 2.333e-02 1.064e-01 3.960e-01 5.279e-02 6.146e-02 2.984e-02 3.604e+01
 4.954e+01 2.512e+02 4.254e+03 2.226e-01 1.058e+00 1.105e+00 2.903e-01
 6.638e-01 2.075e-01]
[1.41855000e+01 1.91928392e+01 9.23355025e+01 6.61859045e+02
 9.64749497e-02 1.04080000e-01 8.87943058e-02 4.94785528e-02
 1.80698241e-01 6.26464573e-02 4.09096231e-01 1.20445829e+00
 2.86661859e+00 4.13843643e+01 6.98354020e-03 2.50993719e-02
 3.12257678e-02 1.16784749e-02 2.04023819e-02 3.73508116e-03
 1.63596206e+01 2.55345226e+01 1.07736030e+02 8.94246985e+02
 1.32529045e-01 2.5336

In [17]:
(x_train - np.mean(x_train, axis=0)) / np.std(x_train, axis=0)

array([[-0.74998027, -1.09978744, -0.74158608, ..., -0.6235968 ,
         0.07754241,  0.45062841],
       [-1.02821446, -0.1392617 , -1.02980434, ..., -0.7612376 ,
        -1.07145262, -0.29541379],
       [-0.53852228, -0.29934933, -0.56857428, ..., -0.50470441,
         0.34900827, -0.13371556],
       ...,
       [-1.3214733 , -0.20855336, -1.3143845 , ..., -0.98621857,
        -0.69108476, -0.13148524],
       [-1.24245479, -0.23244704, -1.27759928, ..., -1.7562754 ,
        -1.55125275, -1.01078909],
       [-0.74441558,  1.13188181, -0.72016173, ..., -0.28490593,
        -1.2308599 ,  0.20083251]], shape=(398, 30))

In [18]:
# STANDARD SCALER 적용
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train_zst = scaler.transform(x_train)
x_test_zst = scaler.transform(x_test)
print(x_train[:5])
print(x_train_zst[:5])

[[1.149e+01 1.459e+01 7.399e+01 4.049e+02 1.046e-01 8.228e-02 5.308e-02
  1.969e-02 1.779e-01 6.574e-02 2.034e-01 1.166e+00 1.567e+00 1.434e+01
  4.957e-03 2.114e-02 4.156e-02 8.038e-03 1.843e-02 3.614e-03 1.240e+01
  2.190e+01 8.204e+01 4.676e+02 1.352e-01 2.010e-01 2.596e-01 7.431e-02
  2.941e-01 9.180e-02]
 [1.049e+01 1.861e+01 6.686e+01 3.343e+02 1.068e-01 6.678e-02 2.297e-02
  1.780e-02 1.482e-01 6.600e-02 1.485e-01 1.563e+00 1.035e+00 1.008e+01
  8.875e-03 9.362e-03 1.808e-02 9.199e-03 1.791e-02 3.317e-03 1.106e+01
  2.454e+01 7.076e+01 3.754e+02 1.413e-01 1.044e-01 8.423e-02 6.528e-02
  2.213e-01 7.842e-02]
 [1.225e+01 1.794e+01 7.827e+01 4.603e+02 8.654e-02 6.679e-02 3.885e-02
  2.331e-02 1.970e-01 6.228e-02 2.200e-01 9.823e-01 1.484e+00 1.651e+01
  5.518e-03 1.562e-02 1.994e-02 7.924e-03 1.799e-02 2.484e-03 1.359e+01
  2.522e+01 8.660e+01 5.642e+02 1.217e-01 1.788e-01 1.943e-01 8.211e-02
  3.113e-01 8.132e-02]
 [1.831e+01 1.858e+01 1.186e+02 1.041e+03 8.588e-02 8.468e-02 8.169

In [19]:
# KNN 알고리즘 적용
from sklearn.neighbors import KNeighborsClassifier
cancer_knn = KNeighborsClassifier(n_neighbors=10)
cancer_knn.fit(x_train_zst, y_train)
pred = cancer_knn.predict(x_test_zst)

In [20]:
# 실제 라벨값과 예측값 출력
print(y_test)
print(pred)

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0
 0 1 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1 0
 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0 1 1 1]
[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0
 0 1 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1
 0 0 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0 1 1 0 1 0
 1 1 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0 1 1 1]


In [21]:
#평균 정확도 출력
print(np.mean(y_test == pred))

0.9590643274853801


In [22]:
# K 개수 변하면서 예측값 확률 변화 확인인
for k in range(1,21):
    cancer_knn = KNeighborsClassifier(n_neighbors=k)
    cancer_knn.fit(x_train_zst, y_train)
    pred = cancer_knn.predict(x_test_zst)
    print(k, "==>", np.mean(y_test == pred))

1 ==> 0.935672514619883
2 ==> 0.9122807017543859
3 ==> 0.935672514619883
4 ==> 0.9590643274853801
5 ==> 0.9590643274853801
6 ==> 0.9590643274853801
7 ==> 0.9590643274853801
8 ==> 0.9532163742690059
9 ==> 0.9649122807017544
10 ==> 0.9590643274853801
11 ==> 0.9590643274853801
12 ==> 0.9590643274853801
13 ==> 0.9590643274853801
14 ==> 0.9649122807017544
15 ==> 0.9590643274853801
16 ==> 0.9590643274853801
17 ==> 0.9473684210526315
18 ==> 0.9473684210526315
19 ==> 0.9415204678362573
20 ==> 0.9473684210526315


In [23]:
# 마찬가지로 진행
cancer_knn = KNeighborsClassifier(n_neighbors=13)
cancer_knn.fit(x_train_zst, y_train)
pred = cancer_knn.predict(x_test_zst)
print(k, "==>", np.mean(y_test == pred))

20 ==> 0.9590643274853801


In [24]:
# 컨퓨전 매트릭스 진행
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[ 57,   6],
       [  1, 107]])

In [25]:
# 0. 필요 라이브러리 임포트
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedShuffleSplit

# 1. 필요 변수 세팅

# 1.1 공통
split = StratifiedShuffleSplit(n_splits=10, test_size=0.3, random_state=7)         # 데이터 반복 분할
first = True                                     # 첫 루프에서만 나이브베이즈 모델에 대한 구문에 들어가기 위한.. 꼼수? 방법.

# 1.2. 나이브 베이즈 모델에 쓸 것
nb_cv_acc = []                                   # nb 정확도 저장용 리스트

# 1.3. kNN 모델에 쓸 것
scaler = StandardScaler()                        # 표준화 도구 생성
cancer_zst = scaler.fit_transform(cancer.data)   # z-score 표준화 한 data를 새 변수에 저장
knn_cv_acc = []                                  # knn 정확도 저장용 리스트

# ------------------------------------------------

# 2. 분할된 데이터로 반복 모델링하여 평균 정확도를 저장 + 비교하기 위한 반복문 작성

for k in range(1, 41, 2):      # 적절한 k값을 찾을 범위 지정
  tmp_acc = []                 # 현재 k값에 대한 정확도를 저장할 리스트 for 최적의 k값 찾기

  for train_idx, test_idx in split.split(cancer.data, cancer.target):

    if first:
      cancer_nb = GaussianNB()
      cancer_nb.fit(cancer.data[train_idx], cancer.target[train_idx])
      pred = cancer_nb.predict(cancer.data[test_idx])
      nb_cv_acc.append(np.mean(cancer.target[test_idx] == pred))

    cancer_knn = KNeighborsClassifier(n_neighbors=k)
    cancer_knn.fit(cancer_zst[train_idx], cancer.target[train_idx])
    pred = cancer_knn.predict(cancer_zst[test_idx])
    tmp_acc.append(np.mean(cancer.target[test_idx] == pred))

  knn_cv_acc.append(np.mean(tmp_acc))
  first = False

print(np.mean(nb_cv_acc))
print(np.argmax(knn_cv_acc), knn_cv_acc[np.argmax(knn_cv_acc)])

0.9432748538011696
1 0.968421052631579


# GridSearchCV 사용
- 하이퍼파라미터를 자동으로 튜닝해주는 기능

In [26]:
from sklearn.model_selection import GridSearchCV

# 0. 파라미터 범위 및 목록 지정
param_grid = [{'n_neighbors':range(1,41,2)}]

# 1. 필요한 변수
scaler = StandardScaler()   # 표준화
cancer_zst = scaler.fit_transform(cancer.data)

# 2. 모델 생성
cancer_knn = KNeighborsClassifier()

# 3. 그리드서치
grid_m = GridSearchCV(cancer_knn,     # 사용할 모델 지정
                      param_grid,     # 사용할 파라미터 지정
                      cv=10,          # 시행할 교차검증 횟수 지정
                      return_train_score=True,    # 학습 정확도 저장 여부 지정
                      verbose=3)      # 진행상황 출력

grid_m.fit(cancer_zst, cancer.target)

Fitting 10 folds for each of 20 candidates, totalling 200 fits
[CV 1/10] END n_neighbors=1;, score=(train=1.000, test=0.965) total time=   0.0s
[CV 2/10] END n_neighbors=1;, score=(train=1.000, test=0.930) total time=   0.0s
[CV 3/10] END n_neighbors=1;, score=(train=1.000, test=0.947) total time=   0.0s
[CV 4/10] END n_neighbors=1;, score=(train=1.000, test=0.982) total time=   0.0s
[CV 5/10] END n_neighbors=1;, score=(train=1.000, test=1.000) total time=   0.0s
[CV 6/10] END n_neighbors=1;, score=(train=1.000, test=0.947) total time=   0.0s
[CV 7/10] END n_neighbors=1;, score=(train=1.000, test=0.912) total time=   0.0s
[CV 8/10] END n_neighbors=1;, score=(train=1.000, test=0.947) total time=   0.0s
[CV 9/10] END n_neighbors=1;, score=(train=1.000, test=0.947) total time=   0.0s
[CV 10/10] END n_neighbors=1;, score=(train=1.000, test=0.929) total time=   0.0s
[CV 1/10] END n_neighbors=3;, score=(train=0.979, test=0.982) total time=   0.0s
[CV 2/10] END n_neighbors=3;, score=(train=0.

,estimator,KNeighborsClassifier()
,param_grid,"[{'n_neighbors': range(1, 41, 2)}]"
,scoring,None
,n_jobs,None
,refit,True
,cv,10
,verbose,3
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,True
,n_neighbors,7


In [27]:
grid_m.best_params_

{'n_neighbors': 7}

In [28]:
grid_m.best_score_

np.float64(0.9683897243107771)

In [29]:
from sklearn.pipeline import Pipeline
pip = Pipeline([("preprocess", StandardScaler()),
                ("classifier", KNeighborsClassifier())])
grid_param = [
    {"preprocess":[StandardScaler()],
     "classifier":[KNeighborsClassifier()],
     "classifier__n_neighbors":range(1,40,2)},
    {"preprocess":[None],
     "classifier":[GaussianNB()]}
]

grid_m = GridSearchCV(pip, grid_param, cv=5,
                      return_train_score=True, verbose=3)
grid_m.fit(cancer.data, cancer.target)

Fitting 5 folds for each of 21 candidates, totalling 105 fits
[CV 1/5] END classifier=KNeighborsClassifier(), classifier__n_neighbors=1, preprocess=StandardScaler();, score=(train=1.000, test=0.956) total time=   0.0s
[CV 2/5] END classifier=KNeighborsClassifier(), classifier__n_neighbors=1, preprocess=StandardScaler();, score=(train=1.000, test=0.974) total time=   0.0s
[CV 3/5] END classifier=KNeighborsClassifier(), classifier__n_neighbors=1, preprocess=StandardScaler();, score=(train=1.000, test=0.974) total time=   0.0s
[CV 4/5] END classifier=KNeighborsClassifier(), classifier__n_neighbors=1, preprocess=StandardScaler();, score=(train=1.000, test=0.930) total time=   0.0s
[CV 5/5] END classifier=KNeighborsClassifier(), classifier__n_neighbors=1, preprocess=StandardScaler();, score=(train=1.000, test=0.938) total time=   0.0s
[CV 1/5] END classifier=KNeighborsClassifier(), classifier__n_neighbors=3, preprocess=StandardScaler();, score=(train=0.980, test=0.974) total time=   0.0s
[C

,estimator,Pipeline(step...lassifier())])
,param_grid,"[{'classifier': [KNeighborsClassifier()], 'classifier__n_neighbors': range(1, 40, 2), 'preprocess': [StandardScaler()]}, {'classifier': [GaussianNB()], 'preprocess': [None]}]"
,scoring,None
,n_jobs,None
,refit,True
,cv,5
,verbose,3
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,True
,copy,True
