In [6]:
from sklearn.datasets import load_diabetes
dibt = load_diabetes()

print(dibt.DESCR)

# dibt 데이터는 수치적인 속성들을 여럿 가지고 있음

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have bee

In [7]:
dibt.data.shape

(442, 10)

In [8]:
# 예측하고자 하는 값 확인

dibt.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [9]:
# 데이터 분할

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(dibt.data, dibt.target, random_state = 3)

print(x_train.shape, y_test.shape)

(331, 10) (111,)


In [10]:
from sklearn.linear_model import LinearRegression
dibt_lr = LinearRegression()
dibt_lr.fit(x_train, y_train)

pred = dibt_lr.predict(x_test)

print(pred[:10])
print(y_test[:10])

[ 96.93071611 180.50531222 104.99346721 123.06727745 185.6971835
  80.55682061 126.1862135  233.66341201 156.82400764 170.55080528]
[ 53.  85.  47.  84. 174.  42.  44. 195. 150. 121.]


In [11]:
print(dibt_lr.coef_)        # 회귀 계수
print(dibt_lr.intercept_)   # y절편

[  -1.28406745 -245.942366    542.4812886   332.41309796 -869.22384677
  471.38808685  172.22381203  334.86353979  697.42259397   66.83610853]
153.47873564418862


In [12]:
x_test[0]    # 샘플 하나 확인

array([-0.02730979,  0.05068012, -0.01590626, -0.02977038,  0.00393485,
       -0.00068758,  0.04127682, -0.03949338, -0.02364686,  0.01134862])

In [13]:
# 모델의 예측값 계산 (y = wx + b)

import numpy as np
np.sum(x_test[0] * dibt_lr.coef_) + dibt_lr.intercept_

np.float64(96.93071610847286)

In [14]:
# 성능평가

from sklearn.metrics import mean_squared_error, r2_score
print(mean_squared_error(y_test, dibt_lr.predict(x_test)))
print(r2_score(y_test, dibt_lr.predict(x_test)))

3033.4901113897236
0.4263073920837931


In [15]:
## kNN 회귀, 결정트리회귀

from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

dibt_knn = KNeighborsRegressor(n_neighbors=5)
dibt_knn.fit(x_train, y_train)

pred = dibt_knn.predict(x_test)

print(pred[:10])
print(y_test[:10])

# 평가
from sklearn.metrics import mean_squared_error, r2_score
print(mean_squared_error(y_test, pred))    # MSE
print(r2_score(y_test, pred))              # R2

[ 64.8 158.   66.6 141.6 218.2  80.6 126.6 212.2 137.4 141.6]
[ 53.  85.  47.  84. 174.  42.  44. 195. 150. 121.]
3630.461261261261
0.3134084132690441


In [16]:
# 하이퍼파라미터 조정 : k값
# 여러 k값에 따른 MSE, R2 점수를 출력하여, 최적의 k값을 찾아보자

# 참고) MSE는 작은수록 좋고, R2는 1에 가까울수록 좋음

for k in range(1, 100, 2):
  dibt_knn = KNeighborsRegressor(n_neighbors=k)
  dibt_knn.fit(x_train, y_train)
  pred = dibt_knn.predict(x_test)
  print(k, mean_squared_error(y_test, pred), r2_score(y_test, pred))

1 5549.594594594595 -0.04953742354284163
3 3689.027027027027 0.3023324757637197
5 3630.461261261261 0.3134084132690441
7 3629.025556168413 0.3136799333230643
9 3459.5618952285618 0.34572884267226023
11 3416.5057702330428 0.35387160224240066
13 3308.716989178528 0.3742565794919044
15 3393.451371371372 0.3582316422363446
17 3447.8297016739916 0.34794763108750093
19 3367.0896658431284 0.36321715893106976
21 3343.6002737431313 0.3676594646968334
23 3338.926054599023 0.3685434514158562
25 3330.335365765766 0.37016811953725315
27 3240.1145095713 0.3872306568714935
29 3233.864489935834 0.3884126584381824
31 3167.7123491858138 0.4009233285747442
33 3213.1239090329996 0.3923351099745064
35 3251.5159845559847 0.38507441383859353
37 3258.1943616370213 0.38381140145893144
39 3290.5732181886033 0.37768792322945677
41 3282.395383485806 0.3792345125195091
43 3258.68414872417 0.3837187730932431
45 3268.7812256701145 0.3818092173693921
47 3309.9243593978767 0.37402824205073126
49 3311.3831774298246 0.3

In [17]:
dibt_dt = DecisionTreeRegressor()
dibt_dt.fit(x_train, y_train)
pred = dibt_dt.predict(x_test)
print(mean_squared_error(y_test, pred))

6258.045045045045


In [18]:
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
dibt_rf = RandomForestRegressor()
dibt_rf.fit(x_train, y_train)
pred = dibt_rf.predict(x_test)
print(mean_squared_error(y_test, pred))

3326.585454954955


In [19]:
dibt_ab = AdaBoostRegressor()
dibt_ab.fit(x_train, y_train)
pred = dibt_ab.predict(x_test)
print(mean_squared_error(y_test, pred))

3596.876718997502
